### ISSUE TITLE
Prestashop 1.7+ support

### ISSUE THREAD

**Issue by wouterverweirder** [myparcelnl/prestashop#1]
Right now this plugin doesn't work in Prestashop 1.7+
Any plans on adding support for 1.7+?

**Comment by TimBlom** [comment]
Beste Wouter,

Bedankt voor jouw bericht.

Het klopt dat de huidige koppeling niet werkt voor Prestashop 1.7+.
Momenteel zijn we bezig met de ontwikkeling van een nieuwe Prestashop-plugin.
Ik verwacht niet dat deze plugin op korte termijn compatible met deze versie van Prestashop zal zijn, 
maar uiteraard zal dit wel worden meegenomen in het doorontwikkelen van deze nieuwe update.

Mocht je hier nog verdere vragen over hebben dan hoor ik dat uiteraard graag! Je kan mij bereiken via support@myparcel.nl of 023-3030315

Voor nu wil ik je nog een mooie maandagmiddag toewensen.
