### ISSUE TITLE
Myparcel still acts weirdly (in native checkout)

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#105]
Myparcel still acts weirdly (in native checkout). First request do seem to work, second one not, see: https://dl.dropboxusercontent.com/s/3zj1wuuizi0q2ja/XtiuxH29du.mp4

**Comment by Mitchell-MyParcel** [comment]
@Frankyet We can reproduce this issue and will pick it up. We have also added this specific case to our tests.
