### ISSUE TITLE
Preferred delivery-date is not shown correctly

### ISSUE THREAD

**Issue by Elmoxx** [myparcelnl/prestashop#107]
### Module version

1.4.1

### PrestaShop version

1.7.7.8

### PHP version

7.3.33

### What went wrong?

While placing an order the customer can set it's preferred date for receiving it's order..

That selected date is not shown anywhere within the BO. Not in the order-detail-page and also not on the page with the overview of all orders. (This bug-issue is about the 'overview with all orders-page' only)

Concrete issue:
In this overview with all orders there is a column: 'Delivery-date' but all orders are show with the same date (the date on which the order was created), the preferred delivery-date is not shown.

### Reproduction steps

1. Set Myparcel module to give customer the option the select it's preferred delivery-date
2. Place an order with a delivery-date a few days in the future
3. See page with all orders in BO
4. Check column Delivery-date

**Comment by EdieLemoine** [comment]
Hi @Elmoxx, this bug does not occur anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1). The delivery dates should be displayed neatly in the order grid. :)

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
