### ISSUE TITLE
No Pick Up Points shown?

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/prestashop#11]
This issue was originally posted by: **remboyudo**
Other contributers: **kennethbruyninckx**

**Description**
In v 3.0.1 on myparcelbe/prestashop I do not get pick-up for DPD nor PostNL.

**Software**
PS v1.7.7.2 
Standard checkout
Plugin v 3.0.1. (BE)
Plugin v 1.0.1 (NL)

**Comment by Mitchell-MyParcel** [comment]
Hi everyone, starting last week our internal developers are also actively fixing issues for Prestashop. The good news is that now we have more people working on the plugin. The bad news is that in the process of mirroring our repo with the repo of the external developer we have lost all open issues. We have however managed to recover them in plain text and I will recap them as best as I can, so that at least all relevant information that has been provided by you is available.

**Comment by EdieLemoine** [comment]
I'm getting pickup locations for DPD and PostNL, does this still apply?

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest release.
