### ISSUE TITLE
Orders with multiple shipments only show one in order grid

### ISSUE THREAD

**Issue by Mouzarty** [myparcelnl/prestashop#111]
### Module version

1.4.1

### PrestaShop version

1.7.7.7

### PHP version

7.3

### What went wrong?

Already existing shipments consisting of multiple packages only show one package in order overview.
PS. 1.7.7.7 - MyParcel version 1.4.1

### Reproduction steps

1. Navigate to Orders.
2. Click on order with multiple packages which are already added with previous version of module.
3. See in order overview page that only one tracking number is shown.

**Comment by Mouzarty** [comment]
Any feedback would be nice...

**Comment by Mouzarty** [comment]
Nearly two months without any reply. What do we need to do to have a working solution or at least some communication? We have been here before. You promised better communication and faster and more regular software updates. I have to seriously consider to look for a more reliable shipping partner.

**Comment by EdieLemoine** [comment]
Hi @Mouzarty, sorry for the radio silence. We've recently been busy rebuilding the entire module, and just released the first beta version: [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
