### ISSUE TITLE
Wrong shipment costs shown in checkout

### ISSUE THREAD

**Issue by Onno1989** [myparcelnl/prestashop#114]
### Module version

1.4.1

### PrestaShop version

1.7.8.2

### PHP version

7.2.34

### What went wrong?

During the checkout the additional costs are shown wrong. 

Delivery at Home, or work, the additional cost are €1,54 in my case. That is exactly the extra costs for delivery in the evening. Only it is not mandatory to make these extra costs, so it should not be shown in this place. And now it is not even an option, probably because i am not using the Cutoff times at the moment.  

Delivery at a pickup point seems to be for free. But thats not the case, we just don't charge extra. 
Please check the screenshots

I would be glad if these things, i circled in red in the pictures could be removed. 

Could you please tell me which rule on which page i need to adjust or exclude.
![Knipsel2](https://user-images.githubusercontent.com/50022772/150755190-09bfc1f8-6e5d-46f6-86e5-16a68a609ab2.PNG)
![Knipsel1](https://user-images.githubusercontent.com/50022772/150755192-2852bec9-5a54-4407-a863-8272d8277104.PNG)
 

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

Use delivery options and checkout.

**Comment by EdieLemoine** [comment]
Have you tried toggling the "Show prices as" option? You might get your desired result if you set it to "Total price". It's in the General Settings tab of our module's configuration page.

**Comment by Onno1989** [comment]
> Have you tried toggling the "Show prices as" option? You might get your desired result if you set it to "Total price". It's in the General Settings tab of our module's configuration page.

Thanks! Yes, that solved the problem. But don't set it as "Total price", but as "Surcharge". 

But now i discovered a different problem. The delivery options such as evening delivery and morning delivery are not shown. (And i have set the Cutoff times correctly now).  Only the delivery at a pickup point option is shown. 

It does not make a difference if i toggle the "Show prices as" option again. So i guess i will need to open anther case..
