### ISSUE TITLE
Conceptzendingen kunnen aanmaken

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/prestashop#115]
### What problem does this feature solve?

Graag een instelling wanneer er geëxporteerd gaat worden de zendingen als concept te laten aanmaken ipv meteen een barcode te genereren.

### What should the solution look like?

<img width="450" alt="AAAVZD" src="https://user-images.githubusercontent.com/25433104/151809977-334c44f7-d94b-4377-a025-d77093525632.png">

**Comment by RichardPerdaan** [comment]
Fixed in [v1.7.0](https://github.com/myparcelnl/prestashop/releases/tag/v1.7.0)
