### ISSUE TITLE
Postal/ Zip code error Portugal space / without space

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/prestashop#127]
### Module version

Latest

### PrestaShop version

1.7.8.3

### PHP version

?

### What went wrong?

Postal/ Zip code Portugal = 0000 000 (with space between 0000 and 000
BO accept only 0000000 without space
Prestashop will not accept 0000000 without space
Exact information check Case: 01290535

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by wthijmen** [comment]
Hi @Chris707,

Currently im checking your issue.
It is correct that the Prestashop is not making a shipment when the default format for PR postal is not NNNN-NNN.

Make sure to check out the  **International** -> **Locations** -> **Countries** -> **Portugal**:
- Then change the Zip/Postal code format to the default one: **NNNN-NNN**

If you got more questions about the plugin you can also email to:
[support@myparcel.nl](support@myparcel.nl)
