### ISSUE TITLE
After installing version 1.5.0. 

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#129]
### Module version

1.5.0

### PrestaShop version

1.7.8.3

### PHP version

7.4

### What went wrong?

After instralling the latest version, opening the order page will gave the next error.

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "myparcelnl_label" as such route does not exist.").

[Twig\Error\RuntimeError 0]

### Reproduction steps

1. installing the version 1.5.0.
2. Click on order page
3. See error

**Comment by EdieLemoine** [comment]
Hi @Frankyet, can you try clearing your cache? That should clear up this issue. However, that shouldn't be necessary so we'll look into it.

**Comment by Frankyet** [comment]
I have done that, no hlep, de-install module, delete folder myparcelnl and re-installed module 1.5.0. same error.

 

Van: Edie Lemoine ***@***.*** 
Verzonden: dinsdag 22 maart 2022 12:53
Aan: myparcelnl/prestashop ***@***.***>
CC: Frankyet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [myparcelnl/prestashop] After installing version 1.5.0. (Issue #129)

 

Hi @Frankyet <https://github.com/Frankyet> , can you try clearing your cache? That should clear up this issue. However, that shouldn't be necessary so we'll look into it.

**Comment by joerivanveen** [comment]
Hi @Frankyet When you go to Modules -> Module Manager does it say 'Upgrade' next to the MyParcel module (button to the right)? If so the error will most likely be resolved after you click 'Upgrade'.

**Comment by Frankyet** [comment]
No it will not say upgrade, I have also de-installed the old one and also deleted the myparcelnl folder.

 

 

Van: Joeri van Veen ***@***.*** 
Verzonden: dinsdag 22 maart 2022 13:39
Aan: myparcelnl/prestashop ***@***.***>
CC: Frankyet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [myparcelnl/prestashop] After installing version 1.5.0. (Issue #129)

 

Hi @Frankyet <https://github.com/Frankyet>  When you go to Modules -> Module Management does it say 'Upgrade' next to the MyParcel module (button to the right)? If so the error will most likely be resolved after you click upgrade.

**Comment by EdieLemoine** [comment]
@Frankyet we haven't been able to figure out why PrestaShop sometimes doesn't show the "Upgrade" button, but if it's there, clicking it does most likely fix this issue. If you want to force show this button you can downgrade the module version in the database:

```sql
UPDATE <DB_PREFIX>_tab SET version = '1.4.1' WHERE module = 'myparcelnl';
```

Then the "Upgrade" button in the Module Manager should be present. We haven't found a better solution to this so far, we're thinking about adding a button in our module's settings to force upgrade or something similar. 

I hope this workaround can help you for now, this new update contains countless big improvements to the module. We'll continue looking into a better fix tomorrow.

**Comment by Frankyet** [comment]
Changed in database
![image](https://user-images.githubusercontent.com/22242384/159539921-9e6803d1-707d-4ad8-b656-31d2738fd5fd.png)

 



Downgrade to 

![image](https://user-images.githubusercontent.com/22242384/159539956-bdef362d-4036-4120-9dc6-daee504fb6c9.png)


 

Now I have an upgrade button
![image](https://user-images.githubusercontent.com/22242384/159540001-d00b7290-69b6-46c5-8b05-85a663c25b55.png)



After upgrade still error on order page

 
![image](https://user-images.githubusercontent.com/22242384/159540041-1219c923-fbf8-4e18-b43a-383489720f76.png)




 

Van: Edie Lemoine ***@***.*** 
Verzonden: dinsdag 22 maart 2022 17:29
Aan: myparcelnl/prestashop ***@***.***>
CC: Frankyet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [myparcelnl/prestashop] After installing version 1.5.0. (Issue #129)

 

@Frankyet <https://github.com/Frankyet>  we haven't been able to figure out why PrestaShop sometimes doesn't show the "Upgrade" button, but if it's there, clicking it does most likely fix this issue. If you want to force show this button you can downgrade the module version in the database:

UPDATE <DB_PREFIX>_tab SET version = '1.4.1' WHERE module = 'myparcelnl';

Then the "Upgrade" button in the Module Manager should be present. We haven't found a better solution to this so far, we're thinking about adding a button in our module's settings to force upgrade or something similar.

I hope this workaround can help you for now, this new update contains countless big improvements to the module. We'll continue looking into a better fix tomorrow.

**Comment by Frankyet** [comment]
Installed a fresh new Prestshop installation on the server and installed the Module 1.5.0., whent to the order page and also the error: 

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "myparcelnl_label" as such route does not exist.").

[Twig\Error\RuntimeError 0]
