### ISSUE TITLE
Translation of the frontend "blocks"

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [myparcelnl/prestashop#137]
### What problem does this feature solve?

Our client uses MyParcel on websites with only one language and it's not Dutch.

Right now I think that it's not possible to translate frontend blocks, for example:
![image](https://user-images.githubusercontent.com/62615548/162729684-854108d0-b886-4a5d-bba2-72025216f560.png)

We need to translate these blocks and it's mandatory.

### What should the solution look like?

It should be possible to easily translate all texts that are displayed on the front end. Best case scenario: using the translation system that is built into the PrestaShop.

**Comment by RichardPerdaan** [comment]
In version [1.6.0](https://github.com/myparcelnl/prestashop/releases/tag/v1.6.0) it is possible to adjust all texts for the delivery options
