### ISSUE TITLE
Afgeleverd status wordt niet teruggekoppeld

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/prestashop#14]
This issue was originally posted by: **BenjaminVerkleij**
Other contributers: None

**Description**
Bij de Order opties van de module hebben we ingesteld dat de orderstatus aangepast moet worden naar Afgeleverd bij levering, maar deze status komt niet terug vanuit MyParcel.

De status wordt wel goed naar verzonden gezet bij het aanmaken van het verzendlabel.
Dit is nog niet opgelost in 1.0.7. Enig idee wanneer dit opgelost gaat worden?

**Software**
Alle

**Comment by Mitchell-MyParcel** [comment]
We zijn inmiddels actief bezig met een fix voor dit issue. Zodra de fix live gaat laten we een bericht achter in deze thread.

**Comment by jasperslot** [comment]
Ik heb pas onze webshop opgezet in Presta en onze eerste bestelling is gisteren afgeleverd, echter hebben wij nog steeds het issue wat hier beschreven staat. De status blijft op 'verzonden' staan, terwijl het pakket al wel is afgeleverd. 

In de logging zie ik dat er een webhook bericht binnen komt om (denk ik) de status op afgeleverd te zetten:
`
[MYPARCEL] Incoming webhook: {\"data\":{\"hooks\":[{\"shipment_id\":#########,\"account_id\":######,\"shop_id\":#####,\"status\":7,\"barcode\":\"3SMYPA#########\",\"shipment_reference_identifier\":\"7\"}]}}
`
Helaas gebeurt dit dus niet. Terwijl automatisch naar 'verzonden' wel goed gaat.

**Software**
Prestashop 1.7.7.4
MyParcel module: v1.1.3

**Comment by Mitchell-MyParcel** [comment]
@jasperslot : Zou je login gegevens voor je omgeving willen sturen naar support@myparcel.nl? We hebben dit getest en zien werken dus willen graag even kijken wat er op jouw omgeving gebeurt.

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest release.
