### ISSUE TITLE
Rechterkolom verdwijnt deel keuze verzendkopties

### ISSUE THREAD

**Issue by folksterp** [myparcelnl/prestashop#140]
### Module version

1.52

### PrestaShop version

1.7.7.4

### PHP version

 7.3.27

### What went wrong?

Na het kiezen van verzendopties (alleen huisadres bv) verdween deel rechterkolom. Als je hierna op doorgaan drukt, krijg je een failure. Ingestelde verzendoptie avondlevering niet zichtbaar in optielijst. Zonder het kiezen van de opties, verloopt het proces goed. 

### Reproduction steps

verzendopties aangeklikt
doorgaan geklikt
hierna gaat het fout

### Relevant log output

```shell
vv
```

### Additional context

vv

**Comment by EdieLemoine** [comment]
Hoi @folksterp, we hebben net de eerste beta versie [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) live gezet, waarin alles is vernieuwd. Deze bug komt daar niet meer voor.

In [deze issue](https://github.com/myparcelnl/prestashop/issues/226) (Engelstalig) kan je meer informatie vinden.
