### ISSUE TITLE
In the check-out there is no pickup points to select

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#144]
### Module version

1.5.3

### PrestaShop version

1.7.8.3

### PHP version

7.4

### What went wrong?

After installation of the myparcel module 1.5.3. in the check-out there is no service points the select.
![Capture1](https://user-images.githubusercontent.com/22242384/164009229-eb6fbe1f-248b-4bb3-b90b-d16f993c95da.JPG)

![image](https://user-images.githubusercontent.com/22242384/164009304-69a9e860-f07b-42dc-b00c-babf84384860.png)

### Reproduction steps

1. creat an order and go to check-out
2. Click on post.nl for carrier
3. See there is an expend but no map or list for service points

**Comment by JanMiddelkoop** [comment]
Hi,

We're experiencing the same problems with PHP 7.4, PrestaShop 1.7.8.6 and MyParcel module 1.6.1.

**Comment by RichardPerdaan** [comment]
We are currently investigatingt this problem. As soon as we know more we will mention it here.

**Comment by RichardPerdaan** [comment]
When we reset the MyParcel modules, we see that the problem is solved. @Frankyet and @JanMiddelkoop would you guys like to try to rest the module? Keep in mind that all settings of the plugin will be removed and must be set again.

**Comment by Frankyet** [comment]
When I refresh the webhook it will working again for a few days, so every time it is not working I have to refreh the webhook, make this sens?

**Comment by dtccomputers** [comment]
I've the same issue. When using multiple carrier types it's not working correctly. It is using only the first carier. 

But also when changing settings of one carrier, after that it's not using the new settings. 
I think this has to do with prestashop assigning a new id after making changes for the carrier.

**Comment by RichardPerdaan** [comment]
Fixed in [v1.7.0](https://github.com/myparcelnl/prestashop/releases/tag/v1.7.0)
