### ISSUE TITLE
Save shipments as draft instead of "voormelding"

### ISSUE THREAD

**Issue by Xesau** [myparcelnl/prestashop#156]
### What problem does this feature solve?

Currently, when you create a label inside PrestaShop, it is saved as a "voormelding" in MyParcel. However, when something needs to be changed last-minute before the shipment is picked up, you cannot edit the shipment anymore. If the shipment were to be saved as draft and has to be saved as voormelding later, you can still make last-minute changes if necessary. 

### What should the solution look like?

An option inside the module configuration to save shipments as draft instead of "voormelding" by default.

### Relevant log output

```shell
N/A
```

### Additional context

This was requested by a client of ours.

**Comment by RichardPerdaan** [comment]
Duplicated feature:  https://github.com/myparcelnl/prestashop/issues/115

**Comment by RichardPerdaan** [comment]
Fixed in [v1.7.0](https://github.com/myparcelnl/prestashop/releases/tag/v1.7.0)
