### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by Peter4661** [myparcelnl/prestashop#16]
This error was introduced after installation of the module:

Type error: Argument 1 passed to Gett\MyparcelNL\Module\Hooks\Helpers\AbstractAdminOrder::isMyParcelCarrier() must be of the type int, null given, called in /home/xxxxx/domains/xxxxxxxxxxx.nl/public_html/modules/myparcelnl/src/Module/Hooks/OrdersGridHooks.php on line 142

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

++++++++++++++++++++++++++++++++++++++++++++++++

 in modules/myparcelnl/src/Module/Hooks/Helpers/AbstractAdminOrder.php (line 51)
        }        return $allowSetOnlyRecipient;    }    public function isMyParcelCarrier(int $idCarrier): bool    {        $allowedCarriers = array_map('intval', [            Configuration::get(Constant::DPD_CONFIGURATION_NAME),            Configuration::get(Constant::BPOST_CONFIGURATION_NAME),            Configuration::get(Constant::POSTNL_CONFIGURATION_NAME),

**Comment by Mitchell-MyParcel** [comment]
@Peter4661 : Krijg je deze error zodra je naar bestellingen gaat? Zo ja dan zijn we de fix hiervoor nu aan het testen. Ik laat het weten zodra die beschikbaar wordt gesteld.

**Comment by Peter4661** [comment]
Deze fout kwam idd nadat we naar de bestellingen gingen.


Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op ma 29 mrt. 2021 om 11:57 schreef mitchell bokhove <
***@***.***>:

**Comment by Mitchell-MyParcel** [comment]
@Peter4661 Gisterenmiddag is een nieuwe versie beschikbaar gesteld via github: https://github.com/myparcelnl/prestashop/releases/tag/v1.0.2

In deze versie zit in fix die dit probleem verhelpt. Zou je aan kunnen geven of het bij jou op de omgeving ook opgelost is?
