### ISSUE TITLE
Integration with exsisting shipping methodes

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/prestashop#16]
This issue was originally posted by: **Peter4661**
Other contributers: none

**Description**
MyParcel app creates new carrier. The new carrier is not available within existing products. To make this carrier available, all products have to be adjusted, +11,000 in our case :(

**Software**
Alle

**Comment by Mitchell-MyParcel** [comment]
This will be fixed in the next version.

**Comment by Mouzarty** [comment]
Any indication of a release date?

**Comment by Mitchell-MyParcel** [comment]
@Mouzarty We are very close to a release. We have a working fix for this issue locally, have done most acceptance tests and are only waiting on a final retest of some test findings. Expect an update from us tomorrow or Wednesday.

**Comment by Mitchell-MyParcel** [comment]
@Mouzarty: We have just finished testing and approved the plugin for release. We are aiming on a release this week.

**Comment by Mitchell-MyParcel** [comment]
@Mouzarty: v1.1.3. has been made available: https://github.com/myparcelnl/prestashop/releases/tag/1.1.3

You can couple existing shipping options to our plugin by clicking + in the carrier options tab.

**Comment by Mouzarty** [comment]
Oops... Upload failed.

What happened?
This file does not seem to be a valid module zip

Try again

**Comment by RichardPerdaan** [comment]
@Mouzarty,

Did you use the zip file that was included in the release?

![screencast 2021-09-02 16-30-38](https://user-images.githubusercontent.com/11389731/131862766-fe6256e5-2a70-495b-8ec2-5297453fa482.gif)

**Comment by Mouzarty** [comment]
Got it! Thanks.

Installed and configured. There are no buttons to create a shipment in both the orders page and the order detail pages. Am I missing something?

**Comment by Mouzarty** [comment]
It is similar issue to Can't create label from backend issue. I'm using PS 1.7.7.7.

**Comment by Mitchell-MyParcel** [comment]
@Mouzarty: Are you seeing the carrier you chose for this order in the plugin's carrier options tab? If you don't see it please try to add the carrier from this tab with the + symbol. If this does not work can you try creating a new carrier and adding it like this? 

Also we have tested the plugin on PS 1.7.7.7 and are still seeing some issues on this version, namelijk the fact that not all delivery options are loaded directly.

**Comment by Mitchell-MyParcel** [comment]
@Mouzarty We have fixed this issue for some customers by now, by recoupling the carriers and some other configurations. If you have not yet got the plugin to work, please mail your login credentials to support@myparcel.nl and we will check your configuration.
