### ISSUE TITLE
Can't delete webhook, FatalThrowableError

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#161]
### Module version

1.5.0 till 1.6.0

### PrestaShop version

1.7.8.3 and 1.7.8.6

### PHP version

7.4

### What went wrong?

if you want to Delete Webhook in MyParcelNL version 1.6.0 it will give a FatalThrowableError in Prestashop 1.7.8.3. and in a new fresh installed Prestashop 1.7.8.6 it will say Request failed.

### Reproduction steps

1. Navigate to Module manage, MyParcelNL
2. Click on Delete Webhook
3. See ...
![image](https://user-images.githubusercontent.com/22242384/172046943-90fb4d49-6aa9-4dc6-897c-9669a6179e32.png)

and with debug on...
![image](https://user-images.githubusercontent.com/22242384/172046962-d118aff6-a297-4e63-a7e1-56d5d121b177.png)

And in fresh installed Prestashop 1.7.8.6....
![image](https://user-images.githubusercontent.com/22242384/172046998-6010f16c-b9d1-4e8e-bb90-0085e75eb491.png)

**Comment by wthijmen** [comment]
Hi @Frankyet,

We could not reproduce this bug.
It seems it has been solved already in the newer version of the plugin release.
