### ISSUE TITLE
Pick-up location Map will total zoom out if change from carrier and go select again postNL

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#162]
### Module version

1.5.0 till 1.6.0

### PrestaShop version

1.7.8.3 till 1.7.8.6

### PHP version

7.4

### What went wrong?

See video voor issue...
https://imgur.com/a/fNNLsmS

### Reproduction steps

1. Navigate to cart and check-out till you can select postNL
2. Click on ophalen locatie, see map click on another carrier and than back to postNL
3. See MAP

**Comment by EdieLemoine** [comment]
This is likely an issue in [myparcelnl/delivery-options](https://github.com/myparcelnl/delivery-options) and will be resolved in its next major version, which will appear in this module soon after.
