### ISSUE TITLE
Pick-up location point not stored in DB, printed label have no pick-up adres

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#163]
### Module version

1.5.3. till 1.6.0

### PrestaShop version

1.7.8.3 till 1.7.8.6

### PHP version

7.4

### What went wrong?

When customer select pick-u location in the check-out and select create label on that order it will create an label with customer home address and there is no pick-up location point on the label.
Tried to refresh hook no help, reset Myparcel module and reconfigure module no help, tried to de-install module and delete myparcel folder also delete all stored carriers and reinstall myparcelnl module again no help.
You can also not see if a customer did select pick-up point. It is also not showing after the order is payed and showing the overview of the order to the customer, there is only showing select PostNL.
Why not the possibility to select ony pick-up location, than you can create in Prestashop a carrier called PostNL pickup location and activate that in Myparcel module for only pick-up, this will give more advantages like showing the customer that he/she selected pick-up point and also showing on the invoice pdf and it is showing in the back-office as well.
See video…
https://imgur.com/a/zgjunwO

### Reproduction steps

1. Navigate to cart and check-out
2. Click on postNL and select ophalen locatie, finish order
3. See in back-office in order page the order and create label, see that there in no pick-up adres on the label

**Comment by RichardPerdaan** [comment]
Hi @Frankyet,

Thank you for posting your issues.
I see that you are currently experiencing several problems with the MyParcel plugin and we would like to solve all of those for you. We would like to contact you by telephone. 

It is possible to send an email to support@myparcel.nl or call 0233030315.
My IT support colleagues will contact you and we can look into the cause of the problems.

**Comment by RichardPerdaan** [comment]
Hi @Frankyet,
This issue is solved with the latest version ([v1.6.2](https://github.com/myparcelnl/prestashop/releases/tag/v1.6.2)) of the MyParcel plugin. I would like to ask you to use this version.
