### ISSUE TITLE
Warn when incompatible MyParcel settings are chosen for a product

### ISSUE THREAD

**Issue by joerivanveen** [myparcelnl/prestashop#164]
### What problem does this feature solve?

In the module settings of MyParcel we can for instance select 'Mailbox Package' as package type for a specific product in the catalog. However, when the product has a weight that exceeds the maximum of a mailbox package, it will never be selected during checkout. Same may apply for dimensions. It would be nice if the MyParcel module settings for a product would warn when combinations are made that will never work.
Also while working on this probably filtering out combinations that make no sense (such as Age Check + digital stamp) like already happens during shipment creation would be nice.

### What should the solution look like?

Nonsensical combinations can simply be filtered out like during shipment creation.
For settings that conflict with weight or dimension a warning would suffice, so the webshop owner is aware of the incompatibility and can take action, if they want. For the warning the standard PrestaShop messaging should be used imho.

**Comment by EdieLemoine** [comment]
Product settings are vastly improved in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) and this should not be possible anymore.
