### ISSUE TITLE
Can't create label from backend

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/prestashop#17]
This issue was originally posted by: Fabian1974
Other contributers: AdrievandeVreede, BenjaminVerkleij, Mouzarty, JDBKC, Kapotto0

**Description**
Ive installed the latest release of the plugin 1.07 and I haver PS 1.7.7.5.
If I try to create a label I get the announcement "no order found"
Also I only get a create label butten in de orders overview page, on the orderpage itselve I don't get any myparcel block.
I did get this with an earlier version of the plugin.
I did use the postnl created with the installation

**Comment by Mitchell-MyParcel** [comment]
This should be fixed in the latest version. Please check of the carrier is visible in the carrier options tab in our plugin. If this is not the case try coupling the carrier with the + action in this tab. If the carrier is coupled and it still does not show the myparcel actions please create a new carrier and try coupling it in the same way.

**Comment by rockincent** [comment]
I have the same problem. Version 1.1.3 en PS 1.7.7.7

Steps taken
1) removed all carriers in Prestashop
2) created 2 new carriers in Prestashop (PostNL Pakketpost, PostNL Brievenbuspakket)
3) created 2 new entries in MyParcel Carrier Options tab (PostNL Pakketpost, PostNL Brievenbuspakket)
4) Linked in the Carrier Option settings the Prestashop Carrier to the Myparcel Carrier
5) placed order in frontend
6) in the back end in the column "Label" there is no Create button
7) showing details of the order and go to MyParcel block
8) Create New Shipment
9) Error "No Order found"

Please help. This is error keeps poppin up since your release the new version 1.x 

No blackmail intentions :) but please fix this soon. Making labels in the MyParcel back-end by hand is way to time consuming.
Don't want to look for alternative services

**Comment by ghost** [comment]
Edit the two created MyParcel carriers and save it again in the module configuration page.

**Comment by rockincent** [comment]
Did all that. No change

With Old and new API key
1) Tried it on existing order --> error
2) New order --> error
3) Created Webhook in API tab

Now I get error "×An error occurred in MyParcel module, please try again." when creating New shipment in Myparcel block

4) Removed Webhook

Error still the same

**Comment by BenjaminVerkleij** [comment]
The No Order Found error still exists with PS 1.7.7.7 and MyParcel 1.1.3...this is getting quite frustrating to be honest.

**Comment by Mitchell-MyParcel** [comment]
@BenjaminVerkleij: I get that this is getting frustrating. We and our software supplier both have done a deep dive into the issue but have not yet found a fix. We have access to your testing environment so we will do another deep dive this sprint, based on version 1.1.3.

@rockincent: Have you already sent us access to a (testing) environment (login credentials and ftp)? If yes can you please send another reaction on the case mentioning my name? Please add login and ftp credentials if you have not done this yet. Like I said above, we will do another deep dive into this issue based on the latest plugin version.

**Comment by rockincent** [comment]
@Mitchell-MyParcel Did not send you any credentials. I'm fairly new to GitHub. Where can I send the requested info?

**Comment by Mitchell-MyParcel** [comment]
@rockincent : You can send credentials to support@myparcel.nl. Please also mention this github issue.

**Comment by rockincent** [comment]
@Mitchell-MyParcel Any progress or news?

**Comment by Mitchell-MyParcel** [comment]
@rockincent Yes, I have just sent you an email/case reaction with instructions to get the plugin working.

**Comment by rockincent** [comment]
> @rockincent Yes, I have just sent you an email/case reaction with instructions to get the plugin working.

@Mitchell-MyParcel did you send it to the email address which I send you the credentials with? Didn't receive is yet.

**Comment by Mitchell-MyParcel** [comment]
@rockincent: Yes to helpdesk@****.nl on 11:57. My mail contained more info but the most important info were the steps to get everything working (on your test environment I was able to create labels after these steps):

- De carriers zijn om een of andere reden niet goed gekoppeld. Maak daarom een nieuwe carrier aan voor brievenbuspakketjes en een nieuwe voor pakketten. 

- Koppel die nieuwe carriers aan de plugin door in de carrier options tab van de plugin op de plus te drukken.

- De pakketdienst zou nu moeten werken, maar vul voor de zekerheid bij beide vervoerders in de plugin de cut off tijden in per dag door op wijzig te drukken bij de carrier in de carrier options tab. 

- Ik begrijp niet goed waarom het volgende fout gaat dus dat gaan we onderzoeken, maar vul ook een default customs code in in de customs tab.

**Comment by rockincent** [comment]
Didn't receive the email. Did what you suggest in the ticket but still getting the error "no orders found" but tried it on existing orders. Or will it only work on newly created orders?

**Comment by Mitchell-MyParcel** [comment]
@rockincent : We have a fix for this issue but since an extensive amount of code was changed for this fix we still need to do some testing. We are aiming on a release later this week. We will place an update in this thread as soon as we know the release date.

**Comment by Mitchell-MyParcel** [comment]
@rockincent @BenjaminVerkleij Testing is done and we will release the plugin next Monday. If you wish to have it earlier, please contact support@myparcel.nl. If you already have contact with support, they might send you a download link today. There is still a small error in the versioning (which is also the reason why we don't release today) but this has no functional consequences.

**Comment by fjutt64** [comment]
@Mitchell-MyParcel Geweldig nieuws!! Ik kijk ernaar uit.

**Comment by fjutt64** [comment]
@Mitchell-MyParcel @EdieLemoine 
Thank you so much!!! Looks like this one is working. I could make a shipment and the pickups carrier selection work!! :)
Super happy. Will be testing more in coming week.

Thanks
Frans
