### ISSUE TITLE
Bug - pickup order label creation doesn't work

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [myparcelnl/prestashop#170]
### Module version

v1.6.1

### PrestaShop version

1.7.7.1

### PHP version

7.3

### What went wrong?

It's not possible to create an order label for pickup.

### Reproduction steps

Any order label creation leads to this problem in our case.

### Relevant log output

```shell
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment::setPickupCountry() must be of the type string, null given, called in <path>/modules/myparcelnl/vendor/myparcelnl/sdk/src/Helper/Utils.php on line 26" at <path>/modules/myparcelnl/vendor/myparcelnl/sdk/src/Model/Consignment/HasPickupLocation.php line 151 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to MyParcelNL\\Sdk\\src\\Model\\Consignment\\AbstractConsignment::setPickupCountry() must be of the type string, null given, called in <path>/modules/myparcelnl/vendor/myparcelnl/sdk/src/Helper/Utils.php on line 26 at <path>/modules/myparcelnl/vendor/myparcelnl/sdk/src/Model/Consignment/HasPickupLocation.php:151)"} []
```

### Additional context

When ConsigmentAdapter tries to `setPickup`, the pickup data doesn't contain the `cc` index in the array:

```php
[pickup] => Array
        (
            [location_name] => <anonymized>
            [city] => <anonymized>
            [postal_code] => <anonymized>
            [street] => <anonymized>
            [number] => <anonymized>
            [number_suffix] => 
            [location_code] => <anonymized>
            [retail_network_id] => <anonymized>
        )
```

**Comment by wthijmen** [comment]
Hi @mariuszsienkiewicz,

We are currently investigating this bug, for now we can't reproduce the bug.
Im running on the following versions:

- Pestashop 1.7.8.6
- PHP 7.4.29
- Plugin 1.6.1

Is it possible for you to provide us more information about the bug?
I can see that all other values at your side are being set except the CC.

This information can also been shared to the IT-support department trough the following email:
[support@myparcel.nl](mailto:support@myparcel.nl)

**Comment by mariuszsienkiewicz** [comment]
I have sent an email with more information.

**Comment by EdieLemoine** [comment]
The [first beta version](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) of the next version of our module is out now where this should not occur anymore. 

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version, if you're interested in trying it out.
