### ISSUE TITLE
Foutmeldingen in bestellingen pagina

### ISSUE THREAD

**Issue by hostingnetworknl** [myparcelnl/prestashop#19]
Helaas zijn er nog steeds foutmeldingen in de MyParcel module voor Prestashop.
In de backend onder bestellingen zien we:

`<button class="btn btn-outline-secondary addLabel" type="button" data-toggle="modal" data-order-id="16713" data-label-options='{"package_type":1,"package_format":1,"only_to_recipient":false,"age_check":false,"signature":false,"insurance":false,"return_undelivered":false}' data-allow-set-only-recipient="1" data-allow-set-signature="1" data-target="#create" > <i class="material-icons"> label</i> Aanmaken </button>`

Ook op de pagina laat de MyParcel Module niet de gegevens zien.
Sinds de laatste update zijn er ook geen labels meer aan te maken.

We zien graag een oplossing.

**Comment by Mitchell-MyParcel** [comment]
@hostingnetworknl This should be fixed in the latest version: https://github.com/myparcelnl/prestashop/releases/tag/v1.0.4

Please let us know your feedback.
