### ISSUE TITLE
Multicollo export (meerdere pakketlabels) voor EU landen

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/prestashop#19]
In plugin versie 3.2.1 was het mogelijk om meerdere labels aan te maken voor 1 zending, in de nieuwe versie is dit niet meer mogelijk. Dit is wel gewenst.

**Comment by Nikitaverh** [comment]
00875316

**Comment by RichardPerdaan** [comment]
3.2.1 van onze PrestaShop plugin ?
