### ISSUE TITLE
Status update webhook does not update draft shipments

### ISSUE THREAD

**Issue by Xesau** [myparcelnl/prestashop#190]
### Module version

1.7.0

### PrestaShop version

1.7.8.6

### PHP version

7.4

### What went wrong?

When a status change webhook is received, it does not correctly update the status of the shipment in the Orders page if the shipment was created as draft.

    *DEBUG*         v1.7.8.6        2022/09/19 - 16:21:06: Incoming webhook: [{"shipment_id":141185473,"account_id":109666,"shop_id":20251,"status":3,"barcode":"3SUADL214393826","event":"shipment_status_change"}]

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by EdieLemoine** [comment]
Hi @Xesau, this may be solved in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version. If this still applies, feel free to reopen or create a new issue.
