### ISSUE TITLE
Order status when label created not working

### ISSUE THREAD

**Issue by gilemon** [myparcelnl/prestashop#191]
### Module version

1.7.0

### PrestaShop version

1.7.8.9

### PHP version

7.4.3

### What went wrong?

When configuring Order settings >Order status when label created > to "shipped"
After a label is successfully created in the order view, the status of the order does not change to "shipped".
Should WebHook be created?
How to verify it works?

### Reproduction steps

1.  Navigate to Order view
2. Click New shipment & print
3. Click Save
4. See PDF is displayed
5. Refresh order view
6. Order status is not updated

**Comment by gilemon** [comment]
I have enable "Api logging"and now I see some logs in var/logs/myparcelnl.log like:

```
*DEBUG* 	v1.7.8.7	2022/09/24 - 18:21:22: Downloading labels 141618753
*DEBUG* 	v1.7.8.7	2022/09/24 - 18:21:22: Incoming webhook: [{"shipment_id":141618753,"account_id":133603,"shop_id":47487,"status":2,"barcode":"3SXDXU543332967","shipment_reference_identifier":"199818","event":"shipment_status_change"}]
*DEBUG* 	v1.7.8.7	2022/09/24 - 18:21:23: Finished downloading labels as link in 745 ms
```

**Comment by gilemon** [comment]
As a quick fix, I have added this code:


        $order_state = Configuration::get(Constant::LABEL_CREATED_ORDER_STATUS_CONFIGURATION_NAME);

        $with_email = Constant::STATUS_CHANGE_MAIL_CONFIGURATION_NAME;

        $currentOrderState = $order->getCurrentOrderState();

        ApiLogger::addLog('Updating status check: ');

        if ($currentOrderState->id !== $order_state) {

            ApiLogger::addLog('Updating status do: ');

            $history = new \OrderHistory();

            $history->id_order = $order->id;

            $history->id_employee = (int) \Context::getContext()->employee->id;

            $history->changeIdOrderState($order_state, $order);

            $history->add();

            if ($with_email) {

                $history->sendEmail($order);

            }

        }


Ligne 563 in myparcelnl/src/Model/OrderLabel.php

**Comment by EdieLemoine** [comment]
Hi @gilemon, this should not occur anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
