### ISSUE TITLE
Module makes too many database calls to product_configuration

### ISSUE THREAD

**Issue by tajriba** [myparcelnl/prestashop#195]
### Module version

1.7.0

### PrestaShop version

1.7.7.8

### PHP version

7.3

### What went wrong?

The Adminorders /sell/orders/ page does alot of calls to product_configuration myparcelnl table.
When you not use product_configuration options, is slows down the backoffice orders page alot.

### Reproduction steps

See above.

<img width="2487" alt="Schermafbeelding 2022-10-31 om 15 28 35" src="https://user-images.githubusercontent.com/68469531/199037742-a145d24f-26dc-4993-8d41-5afd49eea675.png">

**Comment by EdieLemoine** [comment]
Hi @tajriba, as mentioned in other issues, the [first beta version](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) of the next version of our module is out now where this should be vastly improved.

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version. Feel free to open a new issue if you notice the performance is still not good enough.
