### ISSUE TITLE
Php 7.3 not supported?

### ISSUE THREAD

**Issue by tajriba** [myparcelnl/prestashop#196]
### Module version

1.7.0

### PrestaShop version

1.7.7.8

### PHP version

7.3

### What went wrong?

Error can't use latest version with php version 7.3.

![Schermafbeelding 2022-10-31 om 15 25 21](https://user-images.githubusercontent.com/68469531/199037957-b818fb17-cc1c-4a3b-9941-04dee6d0f45a.jpg)

### Reproduction steps

See above.

**Comment by Frankyet** [comment]
latest version with php version 7.3.? thay one is fased out, what about php version 8.0 and 8.1, Prestshop 8.0.0. is released and supporting php 8.0 and 8.1

**Comment by tajriba** [comment]
We also use php 7.4 but alot of stores with prestashop until version 1.7.8 is only working on php 7.3 or lower.

PrestaShop 8 is not stable enough and just 1 week in the open.

**Comment by EdieLemoine** [comment]
The [first beta version](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) of the next version of our module is out now. It supports PHP 7.4 and above, we do not plan to support PHP 7.3 again (as we haven't for a while).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version, if you're interested in trying it out.
