### ISSUE TITLE
Package type not working

### ISSUE THREAD

**Issue by Kommertje** [myparcelnl/prestashop#199]
### Module version

1.7.1

### PrestaShop version

1.7.8.0

### PHP version

7.4

### What went wrong?

When we create a label form order overview or detail page, with different option then parcel, it always printing 'Parcel'.

We have a Multistore webshop. Now we have change the settings to 'Turn on concept shipment before exporting'. But after printing order status will not update automatic. But after printing the label, the order status is no longer automatically updated.

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by EdieLemoine** [comment]
Hi @Kommertje, this bug does not occur anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
