### ISSUE TITLE
Address not properly recognized if address2 field is in use

### ISSUE THREAD

**Issue by JanMiddelkoop** [myparcelnl/prestashop#2]
We're using the PrestaShop module "auto adres aanvuller" to automatically fill in street/city from a Dutch postal code database (external API).  This module uses the "address2" field as a dedicated house number field.  So "address" is only the street name and "address2" contains the housenumber.  We've configured PrestaShop locale as such also and everything worked fine with the previous versions.

Currently, during checkout, the module complains that the address is not properly filled in after selecting a shipping method.  The exactly error is "Adresgegevens niet ingevuld", coming from the file views/dist/myparcel.js.  Since this file doesn't reference the address2 field, presumably that's where things go wrong.

After the error appears, a form is displayed with only street name filled in and no house number, further suggesting the module left out the address2 field.  The form also doesn't work; when fillling in the house number (again), nothing happens.  It's impossible to complete an order.

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop: As you have probably already read we have released a version which should fix this issue:

https://github.com/myparcelnl/prestashop/releases/tag/v1.0.1

Could you please let us know if the issues has been solved?

**Comment by JanMiddelkoop** [comment]
I can report this specific issue is fixed.  Thanks! :-)  I have another breaking issue with this version however, but I'll open a seperate issue for that.

**Comment by JanMiddelkoop** [comment]
This issue has returned with the latest version of the plugin.  During checkout, I get asked to fill in the house number (which is filled in in address line 2) and filling it in manually again in the MyParcel form that appears doesn't work.

**Comment by JanMiddelkoop** [comment]
After diving into the code, I noticed that including address2 is now a configuration option.  So if you're running into this problem, check the module configuration page.  This should've probably been added to the release note for version 1.0.2.

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop : This has now been added in the latest version as a setting in the general settings tab:

https://github.com/myparcelnl/prestashop/releases/tag/v1.0.4
