### ISSUE TITLE
Allow translating the module

### ISSUE THREAD

**Issue by GravendeelJochem** [myparcelnl/prestashop#203]
### What problem does this feature solve?

The use for Dutch users

### What should the solution look like?

Just a translation of the MyParcel plugin

**Comment by mariuszsienkiewicz** [comment]
Hey! I am bumping this issue, for our client it's important too, we should be able to translate the module for each language turned on for the shop. Right now we can just override text but it's not a good way of handling this. 

The second thing is that not all fields even now are available to override, for example, there is this constant:

https://github.com/myparcelnl/prestashop/blob/8eacdccbdc5d385fdc917ae746781167893ca03a/src/Module/Configuration/Form/CheckoutForm.php#L28

But it's not used in the `getConfig` method nor in this method:

https://github.com/myparcelnl/prestashop/blob/8eacdccbdc5d385fdc917ae746781167893ca03a/src/Service/DeliveryOptionsConfigProvider.php#L113-L148

Another example, the "options" text that's visible in the selected pickup view.

I could create a PR for this but I'm not sure if I will have time to do so.  @EdieLemoine sorry for pinging but is there any real difference between myparcelbe and myparcelnl release/codebase? If I had the time, I could take care of it, but I'm not sure if the BE client version has the same language options as the NL version.

**Comment by EdieLemoine** [comment]
Hi @mariuszsienkiewicz, sorry for the delayed reply. 

We're currently in the process of rewriting the entire plugin to basically solve all open issues and support PS 8 and PHP 8. Therefore, we're probably not going to fix this in the current version, so if you want to do it, you're very welcome to.

MyParcel BE and NL are the same codebase (this repository), so you would only need to make a change once. Thanks in advance if you decide to open a PR! 😄

**Comment by mariuszsienkiewicz** [comment]
@EdieLemoine Unfortunately I had no time to do so but if I see it correctly in the dev branch it's still not done so maybe I will do that eventually. 

By the way, are you working on making the fields translatable for each language that is enabled in each store? The fact It's not working like that is a huge pain right now.

**Comment by EdieLemoine** [comment]
@mariuszsienkiewicz that's correct, we're not adding any features to the current version.

In the new version these fields are not configurable and will be automatically translated into the current language. What language(s) do you need? We currently only have Dutch, English and French, but we now have a system where it's super easy to translate everything into any language.

**Comment by mariuszsienkiewicz** [comment]
Oh, that's even better then! :) When it comes to languages, I'm very happy that Dutch, English, and French will already be supported because we need those languages, but we will also need Polish and German, and we anticipate needing more languages in the future as well. Will the system you mentioned be publicly available? Like Crowdin or something?

**Comment by EdieLemoine** [comment]
@mariuszsienkiewicz not yet, we currently have a [Google Sheet](https://docs.google.com/spreadsheets/d/1TPE7gwG2GXtX7vlKIaskwMy0Xr4o_ir-lsedWB86xyc/edit?usp=sharing) only we can edit that's [imported](https://github.com/myparcelnl/prestashop/blob/3001acb271f5f7567bcf49c58b082535ad4b5e0c/package.json#L28C3-L28C3) whenever the module is built. It's free and pretty convenient (for us), but definitely not ideal for collaboration.

After the big release stuff is out of the way we will look into better ways to manage this and allow other people to contribute. If you're willing to, you can copy the sheet, translate it and send it to me.

**Comment by EdieLemoine** [comment]
Possible in v4.0.0
