### ISSUE TITLE
Exported labels do not get saved

### ISSUE THREAD

**Issue by Xesau** [myparcelnl/prestashop#204]
### Module version

1.7.2

### PrestaShop version

1.7.8.6

### PHP version

7.4.33

### What went wrong?

In the webshop of a client, exported (and printed) labels are not saved to the database (missing from ps_myparcelnl_order_label).

Using "Refresh labels" gives an internal server error (see log output below). This seems to be because $key is NULL, a variable which is only set (in MyParcelCollection.php) if any consignments can be found.

### Reproduction steps

1. Export a label
2. Refresh page
3. Labels do not show up

### Relevant log output

```shell
Oeps ... het lijkt erop dat er een onverwachte fout is opgetreden

Type error: Argument 1 passed to MyParcelNL\Sdk\src\Model\MyParcelRequest::setRequestParameters() must be of the type string, null given, called in /home/sjaalmetverhaal/prestashop/modules/myparcelnl/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php on line 355

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

**Comment by Mark-Ernst** [comment]
Hey Xesau!

I tried to recreate your problem on our own test servers and I couldn't reproduce it. Can you please contact our IT-support department, so we can help you solve this case.

Kind regards,

Mark, MyParcel

**Comment by EdieLemoine** [comment]
This bug does not occur anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
