### ISSUE TITLE
Shipment status is not always up-to-date - bulk refresh feature

### ISSUE THREAD

**Issue by bbrassem** [myparcelnl/prestashop#210]
### What problem does this feature solve?

The shipment status in the Prestashop order overview is not always correct. Possibly because the status update webhooks are not being received properly.

### What should the solution look like?

A bulk-refresh button that lets you manually trigger a status update for a number of shipments (e.g. 100 shipments). The option to trigger a status update for 1 shipment already exists, but updating one by one is time-consuming and impractical.

**Comment by EdieLemoine** [comment]
This is possible in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
