### ISSUE TITLE
[PS8] HTTP 500 error on orders page

### ISSUE THREAD

**Issue by Gleldor** [myparcelnl/prestashop#214]
### Module version

8.1

### PrestaShop version

8.0.1

### PHP version

8.1.15

### What went wrong?

Na de installatie een test bestelling gedaan dit werkt prima daarna in de backoffice op bestellingen geklikt krijg dan de foutmelding en als ik de module uitschakel dan werkt de bestellinspagina weer.

als ik de bestelling weg haal en de module weer aanzet dan krijg ik na het klikken op bebestillingspagina een witte pagina te zien

### Reproduction steps

1. place order
2. go to backend en clic on orders
3. See ...error 500
![1](https://user-images.githubusercontent.com/125903695/220156925-63095caf-463d-4a06-8f0e-96bd5fa9a17c.jpg)
![2](https://user-images.githubusercontent.com/125903695/220156956-aeb17c15-961c-4755-9580-fccab274f141.jpg)

**Comment by wthijmen** [comment]
Hoi @Gleldor!,

Zou je meer informatie met onze collega's van de IT support afdeling kunnen delen?
[support@myparcel.nl](mailto:support@myparcel.nl)

Denk hierbij aan het meesturen van je error log waar de "500 Internal Server Error" hoogstwaarschijnlijk ook in staat.

Met vriendelijke groeten,

Thijmen, MyParcel

**Comment by Gleldor** [comment]
Oei daar vraag je mij wat ik heb geen idee hoe ik die zou moeten krijgen

 

Van: Thijmen Wijers ***@***.***>
Beantwoorden - Aan: myparcelnl/prestashop ***@***.***>
Datum: maandag 20 februari 2023 om 17:24
Aan: myparcelnl/prestashop ***@***.***>
CC: Gleldor ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [myparcelnl/prestashop] HTTP 500 error op bestellingen pagina (Issue #214)

 

Hoi @Gleldor!,

Zou je meer informatie met onze collega's van de IT support afdeling kunnen delen?
***@***.***

Denk hierbij aan het meesturen van je error log waar de "500 Internal Server Error" hoogstwaarschijnlijk ook in staat.

Met vriendelijke groeten,

Thijmen, MyParcel

**Comment by EdieLemoine** [comment]
Merged into #217
