### ISSUE TITLE
Invalid full street exception when address contains extra information

### ISSUE THREAD

**Issue by Xesau** [myparcelnl/prestashop#218]
### Module version

v1.7.2 

### PrestaShop version

1.7.8.6

### PHP version

7.4.33

### What went wrong?

When exporting a consignment for an address that has a second address line, such as the following:

> Rijksweg A27
> -1 Parkeerplaats 't Veentje
> 3755 MN Eemnes
> Nederland

or

> F. Hazemeijerstraat 300
> gebouw CO4
> 7555 RJ Hengelo

The system gives an error "Invalid full street supplied: (address)".
This is thrown in MyParcelNL\Sdk\src\Helper\SplitStreet::validate, because it does not understand how to parse the second part.
This makse it impossible to export packages with a perfectly 

### Reproduction steps

1. Create order with aforementioned address
2. Export order to MyParcel
3. Error: "Invalid full street supplied: Rijksweg A27 -1 Parkeerplaats 't Veentje"

**Comment by EdieLemoine** [comment]
This bug does not occur anymore in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version.
