### ISSUE TITLE
Too many status updates on label scanned

### ISSUE THREAD

**Issue by tajriba** [myparcelnl/prestashop#219]
### Module version

latest

### PrestaShop version

8.0.1

### PHP version

8.1

### What went wrong?

The auto status updates "when label scanned" are setting multiple times to the order

### Reproduction steps

open order

and has this myparcel settings:
<img width="622" alt="Scherm­afbeelding 2023-05-05 om 09 24 37" src="https://user-images.githubusercontent.com/68469531/236399245-eaf3af04-2ef5-4d20-8cec-d1d0f2c76bba.png">
<img width="581" alt="Scherm­afbeelding 2023-05-05 om 09 24 51" src="https://user-images.githubusercontent.com/68469531/236399247-529bbc63-fdd5-4416-893b-b6e1000bc96d.png">
<img width="625" alt="Scherm­afbeelding 2023-05-05 om 09 24 57" src="https://user-images.githubusercontent.com/68469531/236399248-933342b3-49cf-4de6-8073-93387cf6a307.png">

**Comment by EdieLemoine** [comment]
Hi @tajriba, the [first beta version](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) of the next version of our module is out now where the bug you mention does not occur anymore. It also officially supports PS 8+, which the currently stable version of our module does not.

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version, if you're interested in trying it out.
