### ISSUE TITLE
I can't install v1.1.3

### ISSUE THREAD

**Issue by deadlyengineer** [myparcelnl/prestashop#22]
Installation of module myparcelnl failed. The module is invalid and cannot be loaded.

**Comment by Mitchell-MyParcel** [comment]
@Timezone-design: Have you selected the right file and is PHP 7.2 installed on your environment? If yes please contact support@myparcel.nl preferably including credentials and ftp access to a test environment.

![screencast 2021-09-02 16-30-38](https://user-images.githubusercontent.com/11389731/131862766-fe6256e5-2a70-495b-8ec2-5297453fa482.gif)
