### ISSUE TITLE
Insurance delivery-option is not exported

### ISSUE THREAD

**Issue by YoranWattimena** [myparcelnl/prestashop#220]
### Module version

1.8.2

### PrestaShop version

1.7.8.7

### PHP version

7.4.16

### What went wrong?

When I receive multiple orders insured by 100,- and I try to export batch through **Bulk actions** they appear to not be insured in the MyParcel backoffice.

### Reproduction steps

1. Navigate to order overview
2. Click on multiple orders and export them as batch through bulk actions
3. Go back to the MyParcel backoffice and watch how the concept orders are not insured

### Additional context

![Preview1](https://user-images.githubusercontent.com/114222496/236848608-4a585909-1509-4856-a66a-80f6d46a22da.png)
![Preview2](https://user-images.githubusercontent.com/114222496/236848615-4219fe14-9715-444e-a6a7-aefeb21a860b.png)

**Comment by EdieLemoine** [comment]
Should be resolved in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1).
