### ISSUE TITLE
Lots of calls to selectDeliveryOption. resulting in spacing out checkout system

### ISSUE THREAD

**Issue by AaronTajriba** [myparcelnl/prestashop#222]
### Module version

1.8.2

### PrestaShop version

8.0.4

### PHP version

8.1

### What went wrong?

When selecting the carrier the module continuely calls selectDeliveryOption over and over again. 

### Reproduction steps

go to the checkout and select the carrier witch is set in the myparcel module

https://github.com/myparcelnl/prestashop/assets/70962249/04abf038-4f6d-413d-9765-395f60a615f6

**Comment by AaronTajriba** [comment]
it results in spacing out "carrier" in frontoffice

**Comment by EdieLemoine** [comment]
The [first beta version](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1) of the next version of our module is out now where this should not occur anymore. 

Please read [this issue](https://github.com/myparcelnl/prestashop/issues/226) for more information and how to report bugs in the new version, if you're interested in trying it out.
