### ISSUE TITLE
Errors on order page BO in PS8

### ISSUE THREAD

**Issue by mark-app** [myparcelnl/prestashop#225]
### Module version

1.8.2

### PrestaShop version

8.1.1

### PHP version

8.1.1

### What went wrong?

If I want to see the order page in the Backoffice I get an 500 error. After enable debug mode i got the error:

Non-static method Gett\MyparcelNL\Service\WeightService::convertToGrams() cannot be called statically

### Reproduction steps

1. Install the module
2. Navigate to the orders page

### Additional context

<img width="1069" alt="Scherm­afbeelding 2023-10-13 om 16 19 59" src="https://github.com/myparcelnl/prestashop/assets/6554157/6b026cfc-77a6-41b8-b74f-24f900b989ed">

**Comment by EdieLemoine** [comment]
Duplicate of #217
