### ISSUE TITLE
Don't you support v1.0.7 anymore?

### ISSUE THREAD

**Issue by deadlyengineer** [myparcelnl/prestashop#23]
I have been using the v1.0.7
But it stopped working at 31th Aug. When I create the label on the Prestashop backoffice, it creates parcel on myparcel backoffice.
But an error (503) occurs on Prestashop backoffice and it doesn't change the order status.

**Comment by Mitchell-MyParcel** [comment]
@Timezone-design: Could you please contact support@myparcel.nl? v1.0.7 should be functioning normally.
