### ISSUE TITLE
[BETA]: Include address field 2 in resolved address

### ISSUE THREAD

**Issue by YoranWattimena** [myparcelnl/prestashop#230]
### What problem does this feature solve?

When clients fill in their streetname in addressfield_1 and then fill their housenumber in addressfield_2, the myparcel plugin does not support the addressfield_2 in the checkout. So my orders will always be street address only (because MyParcel only reads addressfield_1)

### What should the solution look like?

MyParcel plugin accepting addressfield_2

**Comment by EdieLemoine** [comment]
Is this still not working? (Because it should be)
