### ISSUE TITLE
Cannot export labels

### ISSUE THREAD

**Issue by crillaerts** [myparcelnl/prestashop#236]
### Version check

- [X] My version of the plugin is v2.0.0-beta.0 or above.

### PrestaShop version

8.1.2

### PHP version

8.1

### What went wrong?

I'm working on a new webshop (release date 1/2/24), based on Prestashop 8.1.2 (latest version).
I have use the v2.0.0 beta version for myparcelBE.
Ordering is going fine, but when try to create the label (click on export in admin --> orders),  I receive an error
"notification_action_error
Request failed. Status code: 422. Errors: Shipment validation error (request_id: 1704279946.007165953f8a01bb9)"

The label is not created and the shipping order is not send

![Schermafbeelding 2024-01-03 121154](https://github.com/myparcelnl/prestashop/assets/125560690/07a38b0a-fd26-45fb-819f-bfd9a8e3d1bc)

### Reproduction steps

1. Navigate to Orders 
2. Click on order & button 'Exporteren'
3. See the error
![Schermafbeelding 2024-01-03 121154](https://github.com/myparcelnl/prestashop/assets/125560690/37290944-af1a-4c12-853e-7e728459b27c)

### Relevant log output

```shell
None identified
```

**Comment by EdieLemoine** [comment]
Hi @crillaerts, I've looked up the failed request and it appears your account may not be activated yet. If it's a new MyParcel account you need to manually be activated by us first. You can contact customer service to get this resolved.

**Comment by crillaerts** [comment]
Hi Edie, thank you for your fast response. Your feedback was correct, issue can be closed, everything is working now. (except issue 237)

Met vriendelijke groeten,

Christophe Rillaerts
Zaakvoerder - IT Freelancer
0472 800 892
***@***.******@***.***>

***@***.***
www.ravits.be<http://www.ravits.be/>

Van: Edie Lemoine ***@***.***>
Verzonden: woensdag 3 januari 2024 12:57
Aan: myparcelnl/prestashop ***@***.***>
CC: Christophe Rillaerts ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [myparcelnl/prestashop] Cannot export labels (Issue #236)


Hi @crillaerts<https://github.com/crillaerts>, I've looked up the failed request and it appears your account may not be activated yet. If it's a new MyParcel account you need to manually be activated by us first. You can contact customer service to get this resolved.
