### ISSUE TITLE
Buttons not displaying properly on Orders page in 1.7.7.3

### ISSUE THREAD

**Issue by JanMiddelkoop** [myparcelnl/prestashop#24]
In PrestaShop 1.7.7.3 the DataColumn type can no longer be used in the admin backend for inserting HTML code:
https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-fhhq-4x46-qx77

This causes the buttons on the order screen not to display properly, thus making the MyParcel plugin unusable in the latest version of the 1.7.7 branch.

**Comment by JanMiddelkoop** [comment]
![prestashop-myparcel](https://user-images.githubusercontent.com/2273262/114450247-12769500-9bd6-11eb-9136-08adc4feee93.png)

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop : v 1.0.4. staat inmiddels hier op github. We hebben deze versie getest op Prestashop v1.7.7.3 en 1.7.7.2 en dit issue is daarop gefixed. We hebben ook nog specifiek het 2e adresveld als huisnummer getest. Dit is een setting geworden in de general settings tab.

Zou je aan willen geven of dit probleem op jouw omgeving ook gefixed is?
