### ISSUE TITLE
[BETA]: Blank settings page after upgrade

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#253]
### Version check

- [X] My version of the plugin is v4.0.0-beta.0 or above.

### PrestaShop version

8.1.3

### PHP version

8.1

### What went wrong?

When installing beta.3 it did not will update, after uninstall beta.2 and beta.3 will install, but if you go to the config page from myparcel beta 3 it is blank, noting is working of the myparcel module..

<img width="757" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/1fe263c8-815b-4b82-96dd-88cd069e3ed1">

### Reproduction steps

1. Navigate to module page
2. Click on install new module, upload beta 3
3. See ... after succesfull installation go to config page, see blank

**Comment by EdieLemoine** [comment]
Hi @Frankyet, is there any error visible in the console? Also, can you try to clear the PrestaShop cache?

**Comment by Frankyet** [comment]
Hello EdieLemoine,

Yes I have cleared also the cache, no help, there are no error shown.

Ik have now installed Beta 3 on mine test shop and I could now go to the config page. why is will not do it on the running shop stay unknown. did some configuration.
But the the automatic order status saving will not work.

<img width="538" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/bcdb1b27-858d-4ef2-bb9e-8583056bc81b">


On the order page there are no posibilities to creat any label.

<img width="497" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/7cc21d48-6774-412b-a900-891f151ebb96">

**Comment by EdieLemoine** [comment]
Still nothing in the browser console? Can you clear your browser cache or do a hard refresh?

Can you try the "Handmatig bijwerken" button in the settings? 

Does the checkout work, e.g. does our delivery options module load?

Is there anything noteworthy in the log files? They're located in `<prestashop installation>/var/logs/myparcelnl/*.log`. Preferably only `error.log` and `warning.log`.

**Comment by Frankyet** [comment]
Clearing browser cache done but no help.
"Handmatig bijwerken" done but will not safe.
The Checkout will not work because I am using OnePage-Checkout an still waiting for Compatibility with TheCheckout #231 and [Compatibility with Custom Checkout #153 and Compatibility with One Page Checkout #93.

There are error files in folder var/logs/myparcel, I am sending it by e-mail to support@myparcel.nl

**Comment by mariuszsienkiewicz** [comment]
@Frankyet I know that a blank configuration page can also occur when hooks aren't registered due to installation issues. Please follow these steps to check if this is a problem in your case:

1. Select Design -> Positions.
2. Click the Transplant a module button in the top right corner.
3. In the module field, select the myparcel module.
4. Check the field below (I believe the name of this field is "Transplant to"); every hook in the dropdown should be registered. If they're not, it's likely the reason your configuration page is blank, and you'll need to manually "transplant" each hook for this module.

**Comment by Frankyet** [comment]
Hello Mariuszsienkiewicz, thanks for your respons..

I have cheched but tay are hooked.

<img width="578" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/c2b1a007-efb0-4120-90a4-12566d0396f7">

**Comment by Frankyet** [comment]
After delete all myparcel-tables manualy in the database and re-installed (fresh) the myparcel module it did showing the myparcel label printing in the order page.

<img width="199" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/65299c12-36e2-44c3-8120-38adcee39548">
  


with this action there is no history left of the previous made lables.
<img width="346" alt="image" src="https://github.com/myparcelnl/prestashop/assets/22242384/00f3a429-39c6-4201-a3e6-0f091670b31e">

**Comment by EdieLemoine** [comment]
This should be fixed or at least improved. A lot of work has been done on the flaky update/install flow but there are still some weird behaviors. I'm going to make a general issue about installation/upgrade problems to try and keep track of which issues are still occurring.
