### ISSUE TITLE
[BETA]: 4 will not upgrade beta 2 and after de-install it will install but give white page on config.

### ISSUE THREAD

**Issue by Frankyet** [myparcelnl/prestashop#268]
### Version check

- [X] My version of the plugin is v4.0.0-beta.0 or above.

### MyParcelNL version

v.2.0.0. beta

### PrestaShop version

8.1.3.

### PHP version

8.1

### What went wrong?

[BETA]: 4 will not upgrade beta 2 and after de-install it will install but give white page on config.
also if i delete all myparcel tables in database and remove myparcel data in config table. no help.
clear cache no help.

### Reproduction steps

1. Navigate to backoffice
2. Click on module manager
3. upload beta 4 zip
4. clicl on config if it did install
5. see white page
6. also on order page no myparcel adding for labels

### Additional context

[BETA]: 4 will not upgrade beta 2 and after de-install it will install but give white page on config.
also if i delete all myparcel tables in database and remove myparcel dataa in config table.

**Comment by Frankyet** [comment]
After deleteing all tables from myparcel in the database 
<img width="205" alt="image" src="https://github.com/user-attachments/assets/c8c9b3c4-91bf-4c1c-904d-3482ea03f3e7">

and reset module and clear browser cache a few time it did load the config page, anered the key but say it is wrong.
but after get out the module nd back to the myparcel config page it say it is connected to myparcel.

**Comment by EdieLemoine** [comment]
This _should_ be resolved or at least improved. There's another PR that will fix further upgrade issues (#271)
