### ISSUE TITLE
Module installation fails

### ISSUE THREAD

**Issue by dewebspecialist** [myparcelnl/prestashop#282]
### MyParcelNL version

4.0.0

### PrestaShop version

1.7.8.11

### PHP version

7.4.33

### What went wrong?

Downloaded the 4.0.0 file from Github and tried to install.

### Reproduction steps

- Ga naar Module manager
- Klik op Upload een module
- Selecteer het bestand myparcelnl-prestashop-4.0.0.zip in de popup
- Error: "Oeps... uploaden niet gelukt."
- Als je "Wat is er gebeurd?" klikt, krijg je onderstaande meldingen

### Relevant log output

```shell
ClassNotFoundException
HTTP 500 Internal Server Error
Attempted to load trait "HasPdkCheckoutDeliveryOptionsHooks" from namespace "MyParcelNL\PrestaShop\Hooks".
Did you forget a "use" statement for another namespace?

Symfony\Component\Debug\Exception\ ClassNotFoundException
in modules/myparcelnl/myparcelnl.php (line 26)

        \defined('_PS_VERSION_') or exit;
        require_once __DIR__ . '/vendor/autoload.php';
        /**
         * @final
         */
        class MyParcelNL extends \CarrierModule
        {
            use HasPdkCheckoutDeliveryOptionsHooks;
            use HasPdkCheckoutHooks;
            use HasPdkOrderGridHooks;
            use HasPdkOrderHooks;
```

**Comment by RichardPerdaan** [comment]
Hi @dewebspecialist ,

Thank you very much for reporting the error. We appreciate your attentiveness and for taking the time to inform us. Our team is currently investigating the issue, and we are doing our best to resolve it as quickly as possible.

If you have any questions or additional information in the meantime, please don't hesitate to contact us. We will, of course, keep you updated on the progress.

Thank you again for your understanding and cooperation.

**Comment by rwijbenga** [comment]
Any update on a new fixed version?

**Comment by RichardPerdaan** [comment]
Unfortunately, we haven’t been able to replicate the issue in our testing environments yet. However, our developers are actively working to find a solution.

Once we have a fix, I will update you here.

**Comment by RichardPerdaan** [comment]
@dewebspecialist  & @rwijbenga,

Unfortunately, we are still facing a mystery. Since we cannot see this error ourselves, we suspect it might be related to the cache. Could you try clearing the cache?

If this does not solve the issue, we will continue searching for a solution. However, it might be more convenient to have phone contact at that point.

**Comment by rwijbenga** [comment]
Did not solve the problem, I have a case number from MyParcel: 01926951 So a call would be best indeed.

**Comment by RichardPerdaan** [comment]
It took some searching, but we may have implemented the solution in a new version of the plugin: https://github.com/myparcelnl/prestashop/releases/tag/v4.1.0

**Comment by dewebspecialist** [comment]
Hi Richard,
For me this problem is fixed, I can install the plugin now. 

It throws another error: 
 (1/1) ContextErrorException

Notice: Undefined index: is_recyclable_packaging
in ed9bbde51b33790bef4d17797f7a9a5044c7da03_0.file.order-final-summary.tpl.php line 87
Will report that in a separate issue.
