### ISSUE TITLE
An error occurred in MyParcel module, please try again.

### ISSUE THREAD

**Issue by DerekVerheijen** [myparcelnl/prestashop#32]
When I try to create a label I am getting the error: "An error occurred in MyParcel module, please try again." without any further explanation. 

Module version: v1.1.3 
PS version: 1.7.7.0

**Comment by Mitchell-MyParcel** [comment]
@DerekVerheijen: Do you see anything in the logs (please check if API loggings is activated in the API tab of the plugin, then go to advanced parameters->logs)? We see this error mainly when some required product data is missing. MyParcel errors have the prefix [MYPARCEL]. Could you please share the log in this thread? Be careful not to share sensitive data. If you do not want to share logs online you can also send this issue to support@myparcel.nl.

**Comment by DerekVerheijen** [comment]
This are the errors I got:
![image](https://user-images.githubusercontent.com/56411378/135334142-af3ed299-d0a0-4f7b-9582-bae0f9f3ab54.png)

**Comment by DerekVerheijen** [comment]
@Mitchell-MyParcel Any news on this? It is blocking me from using MyParcel.

**Comment by Mitchell-MyParcel** [comment]
@DerekVerheijen Please fill in the customs code and country of origin in the customs tab of v1.2.0 of the plugin . This will probably solve the issue. If you still run into issues after this, please contact our support department so that we be able to do some debugging.

Are you seeing this error for domestic shipments also btw? Because normally this error should only be thrown for international shipments but in some cases we have also seen this happen for domestic shipments. 

@RichardPerdaan  Could you create a Jira issue for this? I have seen this happen before.

**Comment by DerekVerheijen** [comment]
@Mitchell-MyParcel  I also thought this was the problem so what I did was putting the default on: Skip this product on customs form. This gave no difference. Also filling in a default customs code doesn't make any difference. 
So I tried to change it on the product, but this also didn't make any difference.

The problem appears on all shipping destinations. I now have to create all the labels manually.

**Comment by DerekVerheijen** [comment]
@Mitchell-MyParcel 12 days later, still no response. It takes me everyday about 2-3 hours to manually add the addresses...

**Comment by RichardPerdaan** [comment]
Hi @DerekVerheijen ,
I've done a few tests, but I can't reproduce the problem with the following settings:
![image](https://user-images.githubusercontent.com/11389731/137945963-0579eb27-e769-4f61-9ba5-c987cc18dc9f.png)

Would you like to try these settings in the MyParcel plugin. If this is not the solution then I would like to look further into the problem. It might be more convenient if our IT support department takes a look with you, when it doesn't work.

The IT support department can be reached by telephone, which makes it possible to find the solution faster.

**Comment by DerekVerheijen** [comment]
> Hi @DerekVerheijen , I've done a few tests, but I can't reproduce the problem with the following settings: ![image](https://user-images.githubusercontent.com/11389731/137945963-0579eb27-e769-4f61-9ba5-c987cc18dc9f.png)
> 
> Would you like to try these settings in the MyParcel plugin. If this is not the solution then I would like to look further into the problem. It might be more convenient if our IT support department takes a look with you, when it doesn't work.
> 
> The IT support department can be reached by telephone, which makes it possible to find the solution faster.

This did work for one order. But didn't for an other.

**Comment by Mitchell-MyParcel** [comment]
@DerekVerheijen Since we cannot reproduce this from our side, and because earlier suggestions did not solve the issue, I would like to urge you to contact our support department (support@myparcel.nl). Preferably we would like to have login credentials for a testing environment but maybe we can also find the cause via a remote session.

**Comment by Mitchell-MyParcel** [comment]
For people running into this issue, please check if weight are configured correctly. The plugin multiplies the weight by 1000 if Prestashop is configured in kilograms (because we require grams). Changing the setting to grams (via International->Localisation->Local units) might fix this issue.

**Comment by DerekVerheijen** [comment]
This isn't a solution... I can't change this from KG to Grams. All other systems we use are based on KG. In the previous (working) version this was no issue. I think the calculation has to be done by the module. 

> For people running into this issue, please check if weight are configured correctly. The plugin multiplies the weight by 1000 if Prestashop is configured in kilograms (because we require grams). Changing the setting to grams (via International->Localisation->Local units) might fix this issue.
