### ISSUE TITLE
Delete webhook causes: FatalThrowableError

### ISSUE THREAD

**Issue by DerekVerheijen** [myparcelnl/prestashop#41]
![image](https://user-images.githubusercontent.com/56411378/136095863-31a5fdb6-9e5d-4ec5-88df-578d2e0e7d8c.png)

![image](https://user-images.githubusercontent.com/56411378/136095755-e0d2a8f8-2655-4cc5-a440-0c611a0a198d.png)

![image](https://user-images.githubusercontent.com/56411378/136095654-291649f9-c71a-4855-9714-5c1151339f86.png)

**Comment by RichardPerdaan** [comment]
Hi @DerekVerheijen,
Do you still experience this problem with the current version of the MyParcel plugin?
