### ISSUE TITLE
Open order: FatalThrowable Call to a member function format() on null

### ISSUE THREAD

**Issue by rockincent** [myparcelnl/prestashop#42]
When I try to open an order in the backend --> 500 error.
Cleared cache
Module version 1.20
PS 1.7.7.8

Debug Log:

in modules/myparcelnl/src/Module/Carrier/Provider/DeliveryOptionsProvider.php (line 47)
            if ($this->nextDeliveryDate > $this->deliveryDate) {                $deliveryOptionsArray['date'] = $this->nextDeliveryDate->format('Y-m-d');            }        } else {            $deliveryOptionsArray['date'] = $this->nextDeliveryDate->format('Y-m-d');        }        // Prestashop's formatDate function, (which is used in templates) can't handle our date formats.        $deliveryOptionsArray['date'] = (new DateTime($deliveryOptionsArray['date']))->format('Y-m-d');
DeliveryOptionsProvider->provide(991)

in modules/myparcelnl/src/Module/Hooks/Helpers/AdminOrderView.php (line 83)
                'text' => $this->module->l('Print', 'adminorderview'),                'icon' => 'icon-print',            ],        ];        $deliveryOptionsProvider  = new DeliveryOptionsProvider();        $deliveryOptions          = $deliveryOptionsProvider->provide($order->getId());        $labelList                = $this->getLabels();        $labelListHtml = $this->context->smarty->createData($this->context->smarty);        $labelListHtml->assign([            'labelList'              => $labelList,
AdminOrderView->display()

in modules/myparcelnl/src/Module/Hooks/OrdersGridHooks.php (line 155)
    public function hookDisplayAdminOrderMain($params): string    {        $adminOrderView = new AdminOrderView($this, (int) $params['id_order'], $this->context);        return $adminOrderView->display();    }    private function getOrderId(): int    {        $parts = explode('/', parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
MyParcelNL->hookDisplayAdminOrderMain(array('_ps_version' => '1.7.7.8', 'request' => object(Request), 'route' => 'admin_orders_view', 'id_order' => 991, 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))
in classes/Hook.php (line 990)
        return $output;    }    public static function coreCallHook($module, $method, $params)    {        return $module->{$method}($params);    }    public static function coreRenderWidget($module, $hook_name, $params)    {        return $module->renderWidget($hook_name, $params);

**Comment by BenjaminVerkleij** [comment]
We're having the same issue.

**Comment by rockincent** [comment]
Sendcloud addon is working perfectly

**Comment by rockincent** [comment]
Just installed 1.3.0
Error has gone and labels are created.
Seems to work.. Finally.
Thanks.
Will keep on testing.
