### ISSUE TITLE
PrestaShop 1.7.8 compatibility

### ISSUE THREAD

**Issue by JanMiddelkoop** [myparcelnl/prestashop#49]
Hello. I've seen no word on this yet, so I'm asking the question:

Is the latest release of the module (as of writing 1.2.0) compatible with PrestaShop 1.7.8?
Has it been tested with this version?

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop We (for the main part) did a full regression test on PS 1.7.8 with v1.2.0 of our plugin. Aside from the known issues we have encountered an issue with the shipment options ' Handtekening voor ontvangst' and 'Alleen huisadres'. If these are activated and chosen in the checkout, the options are not exported and shown on the label. We are currently fixing this.

Also we are still testing our status webhook and all relating functionality in PS 1.7.8.

**Comment by Mitchell-MyParcel** [comment]
In addition to the issue mentioned above we have also found that a coupled carrier does not work after upgrading.

**Comment by Mitchell-MyParcel** [comment]
The issue with the shipment options not selected will be fixed in the next release. The fix for coupled carriers is not yet included.

**Comment by Mitchell-MyParcel** [comment]
Was already partially fixed, now completely fixed.
