### ISSUE TITLE
If free shipping is configured, surcharges are calculated without VAT.

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/prestashop#80]
**Description**
Configure free shipping from a certain amount via shipping->preference->handling. When configured like this surcharges will be calculated in the checkout without VAT. These should be calculated with VAT.

For the time being a workaround is adding a new price range to the carrier and not using the handling settings.

**Software**
All versions

**Comment by EdieLemoine** [comment]
Resolved in [v2.0.0-beta.1](https://github.com/myparcelnl/prestashop/releases/tag/v2.0.0-beta.1)
