### ISSUE TITLE
Bad SQL query

### ISSUE THREAD

**Issue by Spiros333** [myparcelnl/prestashop#92]
Order page  not visible, it works only when disabling the parcel plugin V1.3.0

**Bad SQL query
Table 'db812341570.ymzg_carriercar261' doesn't exist**

prestashop 1.7.6.2
PhP 7.2
parcel plugin V1.3.0
![image](https://user-images.githubusercontent.com/85503636/144934807-bbf53c49-2def-4e78-838a-a236d871f708.png)

**Comment by Spiros333** [comment]
hello?

**Comment by RichardPerdaan** [comment]
Hi @Spiros333,

Thank you for posting your issue. The MyParcel plugin does not use the carriercar table. Could it be that you have installed the DHL plugin and that it might cause problems?

**Comment by Spiros333** [comment]
No DHL, has no plugin, DHL is only connected with an API key through the webservices.

When disabling parcel plugin  V1.3.0 the issue is gone.

SO its your module.

**Comment by RichardPerdaan** [comment]
Hi @Spiros333 

I spent 2 hours today trying to reproduce this problem.

I'd like to investigate this further for you, but I don't see any connection between the MyParcel plugin and the db812341570.ymzg_carriercar261 table.

I would like to ask you to contact IT support. Then it will be possible for us to search more specifically and find a solution.

You can reach IT support by email (support@myparcel.nl) or by phone (0233030315)

**Comment by Spiros333** [comment]
This is what causing the problem
![image](https://user-images.githubusercontent.com/85503636/145230748-b180b000-c357-48f6-93a1-92a54614d3a1.png)

**Comment by Spiros333** [comment]
customers complaining that they cannot order due to parcel plugin  V1.3.0
When the complet the order and choose the delivery it doesn't show nothing for procceding for payment.
![image](https://user-images.githubusercontent.com/85503636/145472579-ac4e5c1a-360d-4927-b26b-0138144899ac.png)
![image](https://user-images.githubusercontent.com/85503636/145472617-fe3c0be9-3615-4fe2-a266-174449431eb7.png)

I didn't had the rar file anymore of the old plugin, parcel plugin V1.0.4

so I copy the files from a backup I had of last sunday when the version was still the old one, and paste it over the new plugin, my customers were able to order again.

Can you sent me the rar file for  parcel plugin V1.0.4? for just in case.

Why are you not able to proces a correct working plugin for parcel plugin  V1.3.0 ?

**Comment by Spiros333** [comment]
Maybe an suggestion 

Place the parcel plugin V1.0.4 and parcel plugin V1.3.0 next to each other on your work environment and find the problems or differences?

An plugin should be beter from version1.0.4 to version1.3.0 as its an upgrade or update , but your plugin went from bad to worse.

Called the IT support by email (support@myparcel.nl) or by phone (0233030315) THE JUST TOLD ME TO DOWNGRADE the version.

Are you going to fix this or...?

**Comment by Mitchell-MyParcel** [comment]
@Spiros333: We advise you to upgrade your Prestashop version to 1.7.7.x or higher. Our newest version (and all v1.0.0 versions) is only compatible with PS1.7.7. If v1.0.4. has worked in the past this unfortunately has not been by design.

Supporting ps 1.7.6 with this newest plugin is alas not an option. With ps 1.7.7 many hooks have become deprecated and replaced by new ones, one of which you mentioned in your post above. Our new plugin uses many of these new hooks and as such is not backwards compatible.

If upgrading your plugin is not a possibility than the only version of our plugin that has been tested on v1.7.6.x is our old plugin. You can find this version here: https://github.com/myparcelnl/prestashop-deprecated/releases/tag/v2.3.8

**Comment by Mitchell-MyParcel** [comment]
Since this issue won't be fixed by a new release and because a work around was provided, this issue will be closed.
