### ISSUE TITLE
BUG V1.3.0 - Fresh install 1.3.0 doesn't create column 'extra_options'

### ISSUE THREAD

**Issue by Multipage** [myparcelnl/prestashop#94]
A fresh install of 1.3.0 doesn't create the column  'extra_options' in table 'ps_myparcelnl_delivery_settings'
Opening an order gives a 500 error unless you create the table manually

Haven't tested the update yet.

**Comment by ghost** [comment]
Already fixed in #83

**Comment by Multipage** [comment]
Allright , will close this one
