### ISSUE TITLE
V1.3.0 Label with age check not working in Prestashop 1.7.8.2

### ISSUE THREAD

**Issue by venditdevs** [myparcelnl/prestashop#99]
If you create a label with age check, you'll get an error. No specific information available, no information in the server/debug logs.

![image](https://user-images.githubusercontent.com/14218917/146141879-87c592ad-3f19-4ceb-9323-efa40a7bfbb1.png)

![image](https://user-images.githubusercontent.com/14218917/146141731-bc025afb-95fd-45b9-b0b1-f93b411c170a.png)

**Comment by Mitchell-MyParcel** [comment]
@venditdevs And just to be sure, this is regarding a shipment to the Netherlands? And you have API logging activated in our plugin (tab API settings)?

We have no problem generating age check labels (see screencap below), so if this is indeed a shipment to the Netherlands and API logging is activated and you are not getting any decent errors, then we will probably need to gave a closer look. 

https://user-images.githubusercontent.com/69574208/146152396-fb2bf011-79b7-4f56-8873-228a8909ef96.mov

**Comment by venditdevs** [comment]
Hello @Mitchell-MyParcel ,

Yes, it's a shipment to the Netherlands and API logging is active.

**Comment by Mitchell-MyParcel** [comment]
@venditdevs: Ok, then we will need to take a closer look. Can you share credentials to to a (testing) environment via support@myparcel.nl? If not we can also schedule a remote session.

**Comment by venditdevs** [comment]
@Mitchell-MyParcel, i've send the credentials for de BO and FTP environment to support@myparcel.nl.

**Comment by Mitchell-MyParcel** [comment]
This seems to be solved in the latest release.
